// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGgKSycEtgQsNqO2yzOxIS043fk_SZnl4',
    appId: '1:641318942003:web:d2ac7240d3df7c2bc9fa46',
    messagingSenderId: '641318942003',
    projectId: 'flutter-github-c519c',
    authDomain: 'flutter-github-c519c.firebaseapp.com',
    storageBucket: 'flutter-github-c519c.appspot.com',
    measurementId: 'G-V3E9KH0S62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnz4iTKzv0ms59b7uxjJ5mwFMPkdrKoeg',
    appId: '1:641318942003:android:58c5918c81b9f1ddc9fa46',
    messagingSenderId: '641318942003',
    projectId: 'flutter-github-c519c',
    storageBucket: 'flutter-github-c519c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl9lLGXsUPlu-Fy_WkZtWM25gc4PhbGMg',
    appId: '1:641318942003:ios:5115239a5170344bc9fa46',
    messagingSenderId: '641318942003',
    projectId: 'flutter-github-c519c',
    storageBucket: 'flutter-github-c519c.appspot.com',
    androidClientId: '641318942003-9qm54mto1co9m7k87cq1jdvv0h8j35ii.apps.googleusercontent.com',
    iosClientId: '641318942003-vfoe3on9c7ii0bqgtadfkbc9c4dqf4cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGithub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl9lLGXsUPlu-Fy_WkZtWM25gc4PhbGMg',
    appId: '1:641318942003:ios:282d7fc9dc36ca15c9fa46',
    messagingSenderId: '641318942003',
    projectId: 'flutter-github-c519c',
    storageBucket: 'flutter-github-c519c.appspot.com',
    androidClientId: '641318942003-9qm54mto1co9m7k87cq1jdvv0h8j35ii.apps.googleusercontent.com',
    iosClientId: '641318942003-vt4lkfugda7jpiev2dbljkhk1q8eafbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGithub.RunnerTests',
  );
}
